#!/bin/bash
#
# wpf content - Content generation and management
# Generates AI prompts, creates page structure, imports content
#

CONTENT_TARGET="${1:-help}"
shift

# Find current project
CURRENT_DIR=$(pwd)
if [ -f "$CURRENT_DIR/.wpf-config" ]; then
    PROJECT_DIR="$CURRENT_DIR"
    source "$CURRENT_DIR/.wpf-config"
elif [ -f "$CURRENT_DIR/../.wpf-config" ]; then
    PROJECT_DIR="$CURRENT_DIR/.."
    source "$CURRENT_DIR/../.wpf-config"
else
    echo -e "${RED}Error:${NC} Not in a WPF project directory"
    echo "Run 'wpf discover' first to create configuration."
    exit 1
fi

# Load discovery results if available
DISCOVERY_FILE="$PROJECT_DIR/discovery-results.json"

print_banner
echo -e "${GREEN}Content Management:${NC} $PROJECT_NAME"
echo ""

# =====================================================
# HELPER FUNCTIONS
# =====================================================

# Check if Docker/WordPress is running
check_wordpress() {
    if ! docker-compose ps 2>/dev/null | grep -q "wordpress.*Up"; then
        echo -e "${YELLOW}WordPress not running. Starting...${NC}"
        docker-compose up -d
        sleep 10
    fi
}

# Execute WP-CLI command
wp_cli() {
    docker-compose exec -T wordpress wp "$@" --allow-root 2>/dev/null
}

# =====================================================
# CONTENT GENERATION
# =====================================================

# Generate AI prompts for content creation
generate_prompts() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}Generating AI Content Prompts${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    local prompts_file="$PROJECT_DIR/content-prompts.md"

    cat > "$prompts_file" << EOF
# AI Content Generation Prompts for $COMPANY_NAME

Generated by WPF on $(date +%Y-%m-%d)

Use these prompts with Claude, ChatGPT, or other AI assistants to generate content for your website.

---

## Business Context

**Company:** $COMPANY_NAME
**Type:** ${BUSINESS_TYPE:-Professional Services}
**Location:** ${BUSINESS_CITY:-City}, ${BUSINESS_STATE:-State}
**Tagline:** ${TAGLINE:-}

---

## Homepage Content

### Hero Section
\`\`\`
Write a compelling hero section for $COMPANY_NAME, a ${BUSINESS_TYPE:-professional services} company in ${BUSINESS_CITY:-the region}.

Include:
- A powerful headline (5-8 words)
- A supporting subheadline (15-25 words)
- A call-to-action button text

Tone: Professional, trustworthy, action-oriented
${TAGLINE:+Incorporate the tagline: "$TAGLINE"}
\`\`\`

### Services Overview
\`\`\`
Write a brief introduction to the services offered by $COMPANY_NAME.

The company is a ${BUSINESS_TYPE:-professional services} business.
Write 2-3 sentences that:
- Highlight the company's expertise
- Mention the target audience
- Create urgency or interest

Keep it under 50 words.
\`\`\`

---

## About Page

### Company Story
\`\`\`
Write an "About Us" page for $COMPANY_NAME.

Details:
- Business type: ${BUSINESS_TYPE:-Professional Services}
- Location: ${BUSINESS_CITY:-City}, ${BUSINESS_STATE:-State}
- ${TAGLINE:+Tagline: "$TAGLINE"}

Include sections for:
1. Company mission (2-3 sentences)
2. Our story/history (1 paragraph)
3. Our values (3-4 bullet points)
4. Why choose us (3-4 differentiators)

Tone: Warm, professional, authentic
Length: 300-400 words total
\`\`\`

### Team Introduction
\`\`\`
Write a brief team introduction section for $COMPANY_NAME.

This should be a general paragraph about the team's expertise and commitment.
Do not create fictional team members - just describe the team's qualities.

Length: 50-75 words
\`\`\`

---

## Services Page

### Service Descriptions
\`\`\`
Create ${SERVICE_COUNT:-6} service descriptions for $COMPANY_NAME, a ${BUSINESS_TYPE:-professional services} company.

For each service, provide:
1. Service name (2-4 words)
2. Brief description (25-40 words)
3. Key benefit (1 sentence)
4. Icon suggestion (from: briefcase, chart, shield, users, cog, check, star, heart, leaf, building)

Format as a list with clear separators between services.
Make services relevant to a ${BUSINESS_TYPE:-professional services} business.
\`\`\`

---

## Contact Page

### Contact Introduction
\`\`\`
Write a brief contact page introduction for $COMPANY_NAME.

Include:
- Welcoming message
- Mention of response time
- Encouragement to reach out

Details to reference:
- Phone: ${BUSINESS_PHONE:-}
- Email: ${BUSINESS_EMAIL:-}
- Hours: ${BUSINESS_HOURS:-Mo-Fr 08:00-18:00}
- Location: ${BUSINESS_CITY:-City}, ${BUSINESS_STATE:-State}

Length: 40-60 words
\`\`\`

---

## Testimonials

### Generate Testimonials
\`\`\`
Create 3 realistic testimonial templates for $COMPANY_NAME.

For each testimonial:
1. Quote (30-50 words)
2. Client name placeholder: [Client Name]
3. Client title/company placeholder: [Title, Company]

Testimonials should mention:
- Quality of service
- Professionalism
- Results achieved
- Recommendation

Make them sound authentic, not generic.
\`\`\`

---

## FAQ Section

### Generate FAQs
\`\`\`
Create 5 frequently asked questions for $COMPANY_NAME, a ${BUSINESS_TYPE:-professional services} company.

For each FAQ:
1. Question (clear, specific)
2. Answer (50-100 words, helpful)

Topics to cover:
- Services offered
- Pricing/quotes
- Service area
- Timeline/process
- Contact/support

Make questions realistic based on the business type.
\`\`\`

---

## Meta Descriptions

### SEO Meta Content
\`\`\`
Write SEO meta descriptions for $COMPANY_NAME website pages:

1. Homepage (150-160 characters)
2. About page (150-160 characters)
3. Services page (150-160 characters)
4. Contact page (150-160 characters)

Include:
- Primary keyword relevant to ${BUSINESS_TYPE:-professional services}
- Location: ${BUSINESS_CITY:-City}, ${BUSINESS_STATE:-State}
- Call to action

Each must be exactly within the character limit.
\`\`\`

---

## Usage Instructions

1. Copy the prompt section you need
2. Paste into Claude, ChatGPT, or other AI assistant
3. Review and customize the generated content
4. Add to your WordPress site

**Tips:**
- Always review AI-generated content for accuracy
- Add specific details about your actual services
- Include real testimonials when available
- Verify all contact information is correct

---

*Generated by WPF - WordPress Site Factory*
EOF

    echo -e "${GREEN}AI prompts saved to: $prompts_file${NC}"
    echo ""
    echo "Use these prompts with Claude or ChatGPT to generate content."
    echo ""
}

# Create WordPress page structure
create_pages() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}Creating Page Structure${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    check_wordpress

    local pages_created=0

    # Home page (front page)
    if [ "${PAGE_HOME:-true}" = "true" ]; then
        echo -n "Creating Home page... "
        if ! wp_cli post list --post_type=page --name=home --format=count | grep -q "^[1-9]"; then
            wp_cli post create --post_type=page --post_title="Home" --post_name="home" --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>Welcome to $COMPANY_NAME. We provide professional ${BUSINESS_TYPE:-services} in ${BUSINESS_CITY:-the region}.</p><!-- /wp:paragraph -->"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    # About page
    if [ "${PAGE_ABOUT:-true}" = "true" ]; then
        echo -n "Creating About page... "
        if ! wp_cli post list --post_type=page --name=about --format=count | grep -q "^[1-9]"; then
            wp_cli post create --post_type=page --post_title="About" --post_name="about" --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>Learn more about $COMPANY_NAME and our commitment to excellence.</p><!-- /wp:paragraph -->"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    # Services page
    if [ "${PAGE_SERVICES:-true}" = "true" ]; then
        echo -n "Creating Services page... "
        if ! wp_cli post list --post_type=page --name=services --format=count | grep -q "^[1-9]"; then
            wp_cli post create --post_type=page --post_title="Services" --post_name="services" --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>Explore our range of professional services.</p><!-- /wp:paragraph -->"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    # Portfolio page
    if [ "${PAGE_PORTFOLIO:-false}" = "true" ]; then
        echo -n "Creating Portfolio page... "
        if ! wp_cli post list --post_type=page --name=portfolio --format=count | grep -q "^[1-9]"; then
            wp_cli post create --post_type=page --post_title="Portfolio" --post_name="portfolio" --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>View our recent projects and work.</p><!-- /wp:paragraph -->"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    # Blog page
    if [ "${PAGE_BLOG:-false}" = "true" ]; then
        echo -n "Creating Blog page... "
        if ! wp_cli post list --post_type=page --name=blog --format=count | grep -q "^[1-9]"; then
            wp_cli post create --post_type=page --post_title="Blog" --post_name="blog" --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>Latest news and insights.</p><!-- /wp:paragraph -->"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    # Contact page
    if [ "${PAGE_CONTACT:-true}" = "true" ]; then
        echo -n "Creating Contact page... "
        if ! wp_cli post list --post_type=page --name=contact --format=count | grep -q "^[1-9]"; then
            local contact_content="<!-- wp:paragraph --><p>Get in touch with us today.</p><!-- /wp:paragraph -->"
            contact_content+="<!-- wp:paragraph --><p><strong>Phone:</strong> ${BUSINESS_PHONE:-Contact us}</p><!-- /wp:paragraph -->"
            contact_content+="<!-- wp:paragraph --><p><strong>Email:</strong> ${BUSINESS_EMAIL:-info@example.com}</p><!-- /wp:paragraph -->"
            contact_content+="<!-- wp:paragraph --><p><strong>Hours:</strong> ${BUSINESS_HOURS:-Mo-Fr 08:00-18:00}</p><!-- /wp:paragraph -->"

            wp_cli post create --post_type=page --post_title="Contact" --post_name="contact" --post_status=publish \
                --post_content="$contact_content"
            echo -e "${GREEN}created${NC}"
            ((pages_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    fi

    echo ""
    echo -e "${GREEN}Pages created: $pages_created${NC}"

    # Set front page
    echo ""
    echo -n "Setting front page... "
    local home_id=$(wp_cli post list --post_type=page --name=home --field=ID 2>/dev/null)
    if [ -n "$home_id" ]; then
        wp_cli option update show_on_front page
        wp_cli option update page_on_front "$home_id"
        echo -e "${GREEN}done${NC}"
    else
        echo -e "${YELLOW}skipped (no home page)${NC}"
    fi

    # Set blog page if exists
    if [ "${PAGE_BLOG:-false}" = "true" ]; then
        local blog_id=$(wp_cli post list --post_type=page --name=blog --field=ID 2>/dev/null)
        if [ -n "$blog_id" ]; then
            wp_cli option update page_for_posts "$blog_id"
        fi
    fi

    echo ""
}

# Create service entries
create_services() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}Creating Service Entries${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    check_wordpress

    local count="${SERVICE_COUNT:-6}"
    local services_created=0

    # Check if custom post type exists
    if ! wp_cli post-type exists ${PROJECT_NAME}_service 2>/dev/null; then
        echo -e "${YELLOW}Service post type not found. Creating as regular posts...${NC}"
        local post_type="post"
    else
        local post_type="${PROJECT_NAME}_service"
    fi

    # Service templates based on business type
    local service_names=()
    case "${BUSINESS_TYPE:-Professional Services}" in
        "Professional Services")
            service_names=("Consulting" "Strategy" "Implementation" "Training" "Support" "Analysis" "Audit" "Planning")
            ;;
        "Retail/E-commerce")
            service_names=("Products" "Delivery" "Custom Orders" "Gift Cards" "Loyalty Program" "Returns" "Support" "Wholesale")
            ;;
        "Restaurant/Food")
            service_names=("Dine-In" "Takeout" "Delivery" "Catering" "Private Events" "Gift Cards" "Reservations" "Menu")
            ;;
        "Healthcare")
            service_names=("Consultation" "Diagnosis" "Treatment" "Follow-up" "Prevention" "Emergency" "Rehabilitation" "Wellness")
            ;;
        "Construction/Trades")
            service_names=("New Construction" "Renovation" "Repair" "Maintenance" "Inspection" "Consultation" "Emergency" "Commercial")
            ;;
        "Technology")
            service_names=("Development" "Consulting" "Integration" "Support" "Training" "Security" "Cloud Services" "Analytics")
            ;;
        "Creative/Agency")
            service_names=("Branding" "Web Design" "Marketing" "Content" "Social Media" "Video" "Photography" "Strategy")
            ;;
        *)
            service_names=("Service 1" "Service 2" "Service 3" "Service 4" "Service 5" "Service 6" "Service 7" "Service 8")
            ;;
    esac

    for ((i=0; i<count && i<${#service_names[@]}; i++)); do
        local service_name="${service_names[$i]}"
        local service_slug=$(echo "$service_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

        echo -n "Creating service: $service_name... "

        # Check if exists
        if ! wp_cli post list --post_type="$post_type" --name="$service_slug" --format=count 2>/dev/null | grep -q "^[1-9]"; then
            wp_cli post create \
                --post_type="$post_type" \
                --post_title="$service_name" \
                --post_name="$service_slug" \
                --post_status=publish \
                --post_content="<!-- wp:paragraph --><p>Professional $service_name services from $COMPANY_NAME. Contact us to learn more.</p><!-- /wp:paragraph -->" \
                2>/dev/null

            echo -e "${GREEN}created${NC}"
            ((services_created++))
        else
            echo -e "${YELLOW}exists${NC}"
        fi
    done

    echo ""
    echo -e "${GREEN}Services created: $services_created${NC}"
    echo ""
}

# Generate placeholder content
generate_placeholders() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}Generating Placeholder Content${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    create_pages
    create_services
    generate_prompts

    echo ""
    echo -e "${GREEN}Placeholder content generated!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Review content-prompts.md for AI content generation"
    echo "  2. Edit pages in WordPress admin"
    echo "  3. Replace placeholder text with real content"
    echo ""
}

# Show content help
show_help() {
    echo "Usage: wpf content <command>"
    echo ""
    echo "Commands:"
    echo "  prompts      Generate AI prompts for content creation"
    echo "  pages        Create WordPress page structure"
    echo "  services     Create service/product entries"
    echo "  generate     Generate all placeholder content"
    echo "  help         Show this help message"
    echo ""
    echo "Examples:"
    echo "  wpf content generate    # Create pages, services, and AI prompts"
    echo "  wpf content prompts     # Only generate AI prompts"
    echo "  wpf content pages       # Only create page structure"
    echo ""
}

# =====================================================
# MAIN EXECUTION
# =====================================================

case "$CONTENT_TARGET" in
    prompts)
        generate_prompts
        ;;
    pages)
        create_pages
        ;;
    services)
        create_services
        ;;
    generate|all)
        generate_placeholders
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        echo -e "${RED}Unknown content command: $CONTENT_TARGET${NC}"
        echo ""
        show_help
        exit 1
        ;;
esac
